import re
import secrets
import string
from datetime import date, datetime, timedelta
from typing import Optional

import bcrypt

from db import connect, now_iso, today_local

DEFAULT_TRIAL_DAYS = 30
DEFAULT_PAYMENT_DAYS = 30
WARNING_DAYS = (3, 0)  # avisa 3 días antes y el día del vencimiento

USERNAME_RE = re.compile(r"^[a-z][a-z0-9_-]{1,30}$")
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
ROLES = ("admin", "user")

PASSWORD_COMPLEXITY = [
    (re.compile(r"[a-z]"), "minúsculas"),
    (re.compile(r"[A-Z]"), "mayúsculas"),
    (re.compile(r"\d"), "números"),
    (re.compile(r"[^A-Za-z0-9]"), "símbolos"),
]


class UserError(Exception):
    pass


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def verify_password(password: str, password_hash: str) -> bool:
    if not password_hash:
        return False
    try:
        return bcrypt.checkpw(password.encode("utf-8"), password_hash.encode("utf-8"))
    except ValueError:
        return False


def generate_strong_password(length: int = 14) -> str:
    """Genera password con al menos 1 minúscula, 1 mayúscula, 1 dígito y 1 símbolo."""
    pools = {
        "lower": string.ascii_lowercase,
        "upper": string.ascii_uppercase,
        "digit": string.digits,
        "symbol": "!@#$%&*+-=?",
    }
    chars = [secrets.choice(p) for p in pools.values()]
    all_chars = "".join(pools.values())
    chars += [secrets.choice(all_chars) for _ in range(max(0, length - len(chars)))]
    secrets.SystemRandom().shuffle(chars)
    return "".join(chars)


def validate_password_complexity(password: str) -> None:
    if len(password) < 8:
        raise UserError("La password debe tener al menos 8 caracteres.")
    missing = [name for rx, name in PASSWORD_COMPLEXITY if not rx.search(password)]
    if missing:
        raise UserError("La password debe incluir: " + ", ".join(missing))


def list_users(search: Optional[str] = None) -> list[dict]:
    sql = """SELECT u.*, (SELECT COUNT(*) FROM tenants t WHERE t.owner_id = u.id) AS tenant_count
             FROM users u"""
    params: list = []
    if search:
        sql += """ WHERE u.username LIKE ?
                   OR COALESCE(u.first_name,'')   LIKE ?
                   OR COALESCE(u.last_name,'')    LIKE ?
                   OR COALESCE(u.company_name,'') LIKE ?
                   OR COALESCE(u.email,'')        LIKE ?"""
        like = f"%{search.strip()}%"
        params.extend([like] * 5)
    sql += " ORDER BY u.role DESC, u.username"
    with connect() as con:
        rows = con.execute(sql, params).fetchall()
    return [dict(r) for r in rows]


def get_user(user_id: int) -> Optional[dict]:
    with connect() as con:
        row = con.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
    return dict(row) if row else None


def get_user_by_username(username: str) -> Optional[dict]:
    with connect() as con:
        row = con.execute("SELECT * FROM users WHERE username = ?", (username,)).fetchone()
    return dict(row) if row else None


def authenticate(username: str, password: str) -> Optional[dict]:
    user = get_user_by_username(username)
    if not user:
        return None
    if not verify_password(password, user["password_hash"]):
        return None
    return user


def count_user_tenants(user_id: int) -> int:
    with connect() as con:
        row = con.execute(
            "SELECT COUNT(*) AS c FROM tenants WHERE owner_id = ?", (user_id,)
        ).fetchone()
    return row["c"]


def create_user(
    username: str,
    password: Optional[str] = None,
    role: str = "user",
    company_name: Optional[str] = None,
    first_name: Optional[str] = None,
    last_name: Optional[str] = None,
    phone_cc: Optional[str] = None,
    phone: Optional[str] = None,
    email: Optional[str] = None,
    telegram_chat_id: Optional[str] = None,
    tenant_quota: Optional[int] = None,
) -> tuple[dict, str, bool]:
    """Crea un usuario. Devuelve (user, plain_password, autogenerated).

    Si password es vacío/None, autogenera una fuerte y marca must_change_password=1.
    Si password viene del admin, se usa tal cual y must_change_password=0.
    """
    if not USERNAME_RE.match(username):
        raise UserError(
            "Usuario inválido. Solo minúsculas, números, guion bajo o guion; arranca con letra; 2-31 chars."
        )
    if role not in ROLES:
        raise UserError(f"Rol inválido. Usar uno de: {', '.join(ROLES)}")
    if get_user_by_username(username):
        raise UserError(f"Ya existe un usuario llamado '{username}'.")
    if email and not EMAIL_RE.match(email):
        raise UserError(f"Email inválido: {email}")
    if tenant_quota is not None and tenant_quota < 0:
        raise UserError("Quota inválida (debe ser ≥ 0).")

    autogen = not password
    if autogen:
        password = generate_strong_password()
        must_change = 1
    else:
        validate_password_complexity(password)
        must_change = 0

    # Trial: usuarios 'user' arrancan con DEFAULT_TRIAL_DAYS gratis. Admin = NULL.
    trial_until = None
    if role == "user":
        trial_until = (today_local() + timedelta(days=DEFAULT_TRIAL_DAYS)).isoformat()

    with connect() as con:
        cur = con.execute(
            """INSERT INTO users
               (username, password_hash, role, company_name,
                first_name, last_name, phone_cc, phone,
                email, telegram_chat_id, tenant_quota, must_change_password,
                paid_until, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                username, hash_password(password), role,
                (company_name or "").strip() or None,
                (first_name or "").strip() or None,
                (last_name or "").strip() or None,
                (phone_cc or "").strip() or None,
                (phone or "").strip() or None,
                (email or "").strip() or None,
                (telegram_chat_id or "").strip() or None,
                tenant_quota, must_change,
                trial_until,
                now_iso(),
            ),
        )
        uid = cur.lastrowid
        row = con.execute("SELECT * FROM users WHERE id = ?", (uid,)).fetchone()
    return dict(row), password, autogen


# ---------------- BILLING ----------------

def is_paid(user: dict) -> bool:
    """True si el usuario puede operar (admin siempre, user si paid_until >= hoy)."""
    if not user:
        return False
    if user.get("role") == "admin":
        return True
    pu = user.get("paid_until")
    if not pu:
        return False
    try:
        return date.fromisoformat(pu) >= today_local()
    except ValueError:
        return False


def days_until_due(user: dict) -> Optional[int]:
    """Días hasta el vencimiento. Negativo si ya venció. None si no aplica."""
    if not user or user.get("role") == "admin":
        return None
    pu = user.get("paid_until")
    if not pu:
        return None
    try:
        return (date.fromisoformat(pu) - today_local()).days
    except ValueError:
        return None


def set_paid_until(user_id: int, new_date: date) -> None:
    with connect() as con:
        con.execute(
            "UPDATE users SET paid_until = ?, payment_warning_sent_for = NULL WHERE id = ?",
            (new_date.isoformat(), user_id),
        )


def register_payment(
    user_id: int,
    amount: float,
    days: int,
    currency: str = "USD",
    method: Optional[str] = None,
    notes: Optional[str] = None,
    registered_by: Optional[dict] = None,
) -> dict:
    user = get_user(user_id)
    if not user:
        raise UserError("Usuario no encontrado.")
    if user["role"] == "admin":
        raise UserError("Los administradores no requieren pagos.")
    if days <= 0:
        raise UserError("Los días deben ser mayores a 0.")
    if amount < 0:
        raise UserError("El monto no puede ser negativo.")

    today = today_local()
    current = None
    if user.get("paid_until"):
        try:
            current = date.fromisoformat(user["paid_until"])
        except ValueError:
            current = None
    base = current if current and current > today else today
    new_until = base + timedelta(days=days)

    with connect() as con:
        cur = con.execute(
            """INSERT INTO payments
               (user_id, amount, currency, days, method, notes,
                paid_at, registered_by_id, registered_by_username, covers_until)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                user_id, float(amount), (currency or "USD").strip().upper(),
                int(days),
                (method or "").strip() or None,
                (notes or "").strip() or None,
                now_iso(),
                registered_by["id"] if registered_by else None,
                registered_by["username"] if registered_by else None,
                new_until.isoformat(),
            ),
        )
        pid = cur.lastrowid
        con.execute(
            "UPDATE users SET paid_until = ?, payment_warning_sent_for = NULL WHERE id = ?",
            (new_until.isoformat(), user_id),
        )
        row = con.execute("SELECT * FROM payments WHERE id = ?", (pid,)).fetchone()
    return dict(row)


def list_payments(user_id: int, limit: int = 100) -> list[dict]:
    with connect() as con:
        rows = con.execute(
            "SELECT * FROM payments WHERE user_id = ? ORDER BY paid_at DESC LIMIT ?",
            (user_id, limit),
        ).fetchall()
    return [dict(r) for r in rows]


def list_due_users(within_days: int = 3) -> list[dict]:
    """Devuelve usuarios 'user' cuyo paid_until está dentro del próximo `within_days`,
    o ya vencido hace ≤1 día. Excluye admin."""
    today = today_local()
    until = (today + timedelta(days=within_days)).isoformat()
    yesterday = (today - timedelta(days=1)).isoformat()
    with connect() as con:
        rows = con.execute(
            """SELECT * FROM users
               WHERE role = 'user'
                 AND paid_until IS NOT NULL
                 AND paid_until >= ?
                 AND paid_until <= ?""",
            (yesterday, until),
        ).fetchall()
    return [dict(r) for r in rows]


def mark_warning_sent(user_id: int, for_date: str) -> None:
    with connect() as con:
        con.execute(
            "UPDATE users SET payment_warning_sent_for = ? WHERE id = ?",
            (for_date, user_id),
        )


def send_payment_reminders(notify_module, mail_module, login_url: Optional[str] = None) -> int:
    """Para cada user 'user' próximo a vencer (3, 2, 1, 0 días) o vencido (-1):
    si no se mandó aviso aún para esa fecha de paid_until, mandar Telegram + email
    y marcar payment_warning_sent_for = paid_until. Idempotente."""
    sent = 0
    today = today_local()
    for u in list_due_users(within_days=3):
        pu_str = u.get("paid_until")
        if not pu_str:
            continue
        if u.get("payment_warning_sent_for") == pu_str:
            continue
        try:
            pu = date.fromisoformat(pu_str)
        except ValueError:
            continue
        diff = (pu - today).days
        if diff > 3 or diff < -1:
            continue

        if diff > 0:
            subject = f"Tu cuenta MonitorMaat vence en {diff} día{'s' if diff != 1 else ''}"
            body = (
                f"Tu cuenta vence el {pu_str}. "
                f"Contactá al administrador para renovar y evitar el corte."
            )
        elif diff == 0:
            subject = "Tu cuenta MonitorMaat vence hoy"
            body = (
                f"Tu cuenta vence hoy ({pu_str}). "
                f"Si no se renueva, mañana no podrás ingresar al panel."
            )
        else:
            subject = "Tu cuenta MonitorMaat está vencida"
            body = (
                f"Tu cuenta venció el {pu_str}. "
                f"No podés ingresar al panel hasta renovar."
            )

        try:
            notify_module.send_user(
                u, f"⚠ <b>{subject}</b>\n\n{body}", event_key="payment_warning"
            )
        except Exception:
            pass
        if u.get("email") and mail_module.is_configured():
            try:
                mail_module.send_payment_warning(
                    u["email"], u["username"], subject, body, login_url=login_url,
                )
            except Exception:
                pass
        try:
            notify_module.send_admin(
                f"💸 Aviso de pago enviado a <code>{u['username']}</code> "
                f"({diff} día{'s' if abs(diff) != 1 else ''} → {pu_str})"
            )
        except Exception:
            pass

        mark_warning_sent(u["id"], pu_str)
        sent += 1
    return sent


def clear_must_change_password(user_id: int) -> None:
    with connect() as con:
        con.execute("UPDATE users SET must_change_password = 0 WHERE id = ?", (user_id,))


def update_username(user_id: int, new_username: str) -> dict:
    new_username = (new_username or "").strip().lower()
    if not USERNAME_RE.match(new_username):
        raise UserError(
            "Usuario inválido. Solo minúsculas, números, guion bajo o guion; arranca con letra; 2-31 chars."
        )
    existing = get_user_by_username(new_username)
    if existing and existing["id"] != user_id:
        raise UserError(f"Ya existe un usuario llamado '{new_username}'.")
    with connect() as con:
        con.execute("UPDATE users SET username = ? WHERE id = ?", (new_username, user_id))
    return get_user(user_id)


def reset_password(user_id: int) -> str:
    """Genera password nueva, la setea y marca must_change_password=1. Devuelve la plana."""
    user = get_user(user_id)
    if not user:
        raise UserError("Usuario no encontrado.")
    new_pwd = generate_strong_password()
    with connect() as con:
        con.execute(
            "UPDATE users SET password_hash = ?, must_change_password = 1 WHERE id = ?",
            (hash_password(new_pwd), user_id),
        )
    return new_pwd


def update_user(
    user_id: int,
    company_name: Optional[str] = None,
    first_name: Optional[str] = None,
    last_name: Optional[str] = None,
    phone_cc: Optional[str] = None,
    phone: Optional[str] = None,
    email: Optional[str] = None,
    telegram_chat_id: Optional[str] = None,
    telegram_off: Optional[str] = None,
    telegram_bot_token: Optional[str] = None,
    tenant_quota: Optional[int] = None,
    role: Optional[str] = None,
    new_password: Optional[str] = None,
    enforce_complexity: bool = True,
    clear_must_change: bool = False,
) -> dict:
    user = get_user(user_id)
    if not user:
        raise UserError("Usuario no encontrado.")

    fields = []
    params: list = []

    if company_name is not None:
        fields.append("company_name = ?")
        params.append(company_name.strip() or None)
    if first_name is not None:
        fields.append("first_name = ?")
        params.append(first_name.strip() or None)
    if last_name is not None:
        fields.append("last_name = ?")
        params.append(last_name.strip() or None)
    if phone_cc is not None:
        fields.append("phone_cc = ?")
        params.append(phone_cc.strip() or None)
    if phone is not None:
        fields.append("phone = ?")
        params.append(phone.strip() or None)
    if email is not None:
        em = email.strip()
        if em and not EMAIL_RE.match(em):
            raise UserError(f"Email inválido: {em}")
        fields.append("email = ?")
        params.append(em or None)
    if telegram_chat_id is not None:
        tg = telegram_chat_id.strip()
        fields.append("telegram_chat_id = ?")
        params.append(tg or None)
    if telegram_off is not None:
        fields.append("telegram_off = ?")
        params.append(telegram_off.strip() or None)
    if telegram_bot_token is not None:
        fields.append("telegram_bot_token = ?")
        params.append(telegram_bot_token.strip() or None)
    if tenant_quota is not None:
        if tenant_quota < 0:
            raise UserError("Quota inválida (debe ser ≥ 0).")
        fields.append("tenant_quota = ?")
        params.append(tenant_quota)
    if role is not None:
        if role not in ROLES:
            raise UserError(f"Rol inválido. Usar uno de: {', '.join(ROLES)}")
        fields.append("role = ?")
        params.append(role)
    if new_password is not None and new_password != "":
        if enforce_complexity:
            validate_password_complexity(new_password)
        fields.append("password_hash = ?")
        params.append(hash_password(new_password))
    if clear_must_change:
        fields.append("must_change_password = 0")

    if not fields:
        return user

    params.append(user_id)
    with connect() as con:
        con.execute(f"UPDATE users SET {', '.join(fields)} WHERE id = ?", params)
    return get_user(user_id)


def delete_user(user_id: int) -> None:
    user = get_user(user_id)
    if not user:
        raise UserError("Usuario no encontrado.")
    if count_user_tenants(user_id) > 0:
        raise UserError("El usuario tiene tenants. Borralos antes o reasigná el dueño.")
    with connect() as con:
        # Bloquear borrado del último admin
        admins = con.execute("SELECT COUNT(*) AS c FROM users WHERE role = 'admin'").fetchone()["c"]
        if user["role"] == "admin" and admins <= 1:
            raise UserError("No se puede borrar el último admin.")
        con.execute("DELETE FROM users WHERE id = ?", (user_id,))


def seed_initial_admin(username: str, password_hash: str) -> Optional[dict]:
    """Si no hay usuarios en la DB, crea el admin inicial con el hash bcrypt del env.
    Marca must_change_password=1 para forzar cambio en el primer login.
    También adopta tenants huérfanos (sin owner_id) bajo este admin."""
    with connect() as con:
        count = con.execute("SELECT COUNT(*) AS c FROM users").fetchone()["c"]
    if count > 0:
        return None
    if not username or not password_hash:
        return None

    with connect() as con:
        cur = con.execute(
            """INSERT INTO users
               (username, password_hash, role, company_name, tenant_quota,
                must_change_password, created_at)
               VALUES (?, ?, 'admin', 'Administración', NULL, 1, ?)""",
            (username, password_hash, now_iso()),
        )
        admin_id = cur.lastrowid
        # Adoptar tenants huérfanos
        con.execute("UPDATE tenants SET owner_id = ? WHERE owner_id IS NULL", (admin_id,))
    return get_user(admin_id)
