import re
import secrets
import string
from typing import Optional

import bcrypt

from db import connect, now_iso

USERNAME_RE = re.compile(r"^[a-z][a-z0-9_-]{1,30}$")
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
ROLES = ("admin", "user")

PASSWORD_COMPLEXITY = [
    (re.compile(r"[a-z]"), "minúsculas"),
    (re.compile(r"[A-Z]"), "mayúsculas"),
    (re.compile(r"\d"), "números"),
    (re.compile(r"[^A-Za-z0-9]"), "símbolos"),
]


class UserError(Exception):
    pass


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def verify_password(password: str, password_hash: str) -> bool:
    if not password_hash:
        return False
    try:
        return bcrypt.checkpw(password.encode("utf-8"), password_hash.encode("utf-8"))
    except ValueError:
        return False


def generate_strong_password(length: int = 14) -> str:
    """Genera password con al menos 1 minúscula, 1 mayúscula, 1 dígito y 1 símbolo."""
    pools = {
        "lower": string.ascii_lowercase,
        "upper": string.ascii_uppercase,
        "digit": string.digits,
        "symbol": "!@#$%&*+-=?",
    }
    chars = [secrets.choice(p) for p in pools.values()]
    all_chars = "".join(pools.values())
    chars += [secrets.choice(all_chars) for _ in range(max(0, length - len(chars)))]
    secrets.SystemRandom().shuffle(chars)
    return "".join(chars)


def validate_password_complexity(password: str) -> None:
    if len(password) < 8:
        raise UserError("La password debe tener al menos 8 caracteres.")
    missing = [name for rx, name in PASSWORD_COMPLEXITY if not rx.search(password)]
    if missing:
        raise UserError("La password debe incluir: " + ", ".join(missing))


def list_users(search: Optional[str] = None) -> list[dict]:
    sql = """SELECT u.*, (SELECT COUNT(*) FROM tenants t WHERE t.owner_id = u.id) AS tenant_count
             FROM users u"""
    params: list = []
    if search:
        sql += """ WHERE u.username LIKE ?
                   OR COALESCE(u.first_name,'')   LIKE ?
                   OR COALESCE(u.last_name,'')    LIKE ?
                   OR COALESCE(u.company_name,'') LIKE ?
                   OR COALESCE(u.email,'')        LIKE ?"""
        like = f"%{search.strip()}%"
        params.extend([like] * 5)
    sql += " ORDER BY u.role DESC, u.username"
    with connect() as con:
        rows = con.execute(sql, params).fetchall()
    return [dict(r) for r in rows]


def get_user(user_id: int) -> Optional[dict]:
    with connect() as con:
        row = con.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
    return dict(row) if row else None


def get_user_by_username(username: str) -> Optional[dict]:
    with connect() as con:
        row = con.execute("SELECT * FROM users WHERE username = ?", (username,)).fetchone()
    return dict(row) if row else None


def authenticate(username: str, password: str) -> Optional[dict]:
    user = get_user_by_username(username)
    if not user:
        return None
    if not verify_password(password, user["password_hash"]):
        return None
    return user


def count_user_tenants(user_id: int) -> int:
    with connect() as con:
        row = con.execute(
            "SELECT COUNT(*) AS c FROM tenants WHERE owner_id = ?", (user_id,)
        ).fetchone()
    return row["c"]


def create_user(
    username: str,
    password: Optional[str] = None,
    role: str = "user",
    company_name: Optional[str] = None,
    first_name: Optional[str] = None,
    last_name: Optional[str] = None,
    phone_cc: Optional[str] = None,
    phone: Optional[str] = None,
    email: Optional[str] = None,
    telegram_chat_id: Optional[str] = None,
    tenant_quota: Optional[int] = None,
) -> tuple[dict, str, bool]:
    """Crea un usuario. Devuelve (user, plain_password, autogenerated).

    Si password es vacío/None, autogenera una fuerte y marca must_change_password=1.
    Si password viene del admin, se usa tal cual y must_change_password=0.
    """
    if not USERNAME_RE.match(username):
        raise UserError(
            "Usuario inválido. Solo minúsculas, números, guion bajo o guion; arranca con letra; 2-31 chars."
        )
    if role not in ROLES:
        raise UserError(f"Rol inválido. Usar uno de: {', '.join(ROLES)}")
    if get_user_by_username(username):
        raise UserError(f"Ya existe un usuario llamado '{username}'.")
    if email and not EMAIL_RE.match(email):
        raise UserError(f"Email inválido: {email}")
    if tenant_quota is not None and tenant_quota < 0:
        raise UserError("Quota inválida (debe ser ≥ 0).")

    autogen = not password
    if autogen:
        password = generate_strong_password()
        must_change = 1
    else:
        validate_password_complexity(password)
        must_change = 0

    with connect() as con:
        cur = con.execute(
            """INSERT INTO users
               (username, password_hash, role, company_name,
                first_name, last_name, phone_cc, phone,
                email, telegram_chat_id, tenant_quota, must_change_password, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                username, hash_password(password), role,
                (company_name or "").strip() or None,
                (first_name or "").strip() or None,
                (last_name or "").strip() or None,
                (phone_cc or "").strip() or None,
                (phone or "").strip() or None,
                (email or "").strip() or None,
                (telegram_chat_id or "").strip() or None,
                tenant_quota, must_change,
                now_iso(),
            ),
        )
        uid = cur.lastrowid
        row = con.execute("SELECT * FROM users WHERE id = ?", (uid,)).fetchone()
    return dict(row), password, autogen


def clear_must_change_password(user_id: int) -> None:
    with connect() as con:
        con.execute("UPDATE users SET must_change_password = 0 WHERE id = ?", (user_id,))


def update_username(user_id: int, new_username: str) -> dict:
    new_username = (new_username or "").strip().lower()
    if not USERNAME_RE.match(new_username):
        raise UserError(
            "Usuario inválido. Solo minúsculas, números, guion bajo o guion; arranca con letra; 2-31 chars."
        )
    existing = get_user_by_username(new_username)
    if existing and existing["id"] != user_id:
        raise UserError(f"Ya existe un usuario llamado '{new_username}'.")
    with connect() as con:
        con.execute("UPDATE users SET username = ? WHERE id = ?", (new_username, user_id))
    return get_user(user_id)


def reset_password(user_id: int) -> str:
    """Genera password nueva, la setea y marca must_change_password=1. Devuelve la plana."""
    user = get_user(user_id)
    if not user:
        raise UserError("Usuario no encontrado.")
    new_pwd = generate_strong_password()
    with connect() as con:
        con.execute(
            "UPDATE users SET password_hash = ?, must_change_password = 1 WHERE id = ?",
            (hash_password(new_pwd), user_id),
        )
    return new_pwd


def update_user(
    user_id: int,
    company_name: Optional[str] = None,
    first_name: Optional[str] = None,
    last_name: Optional[str] = None,
    phone_cc: Optional[str] = None,
    phone: Optional[str] = None,
    email: Optional[str] = None,
    telegram_chat_id: Optional[str] = None,
    telegram_off: Optional[str] = None,
    telegram_bot_token: Optional[str] = None,
    tenant_quota: Optional[int] = None,
    role: Optional[str] = None,
    new_password: Optional[str] = None,
    enforce_complexity: bool = True,
    clear_must_change: bool = False,
) -> dict:
    user = get_user(user_id)
    if not user:
        raise UserError("Usuario no encontrado.")

    fields = []
    params: list = []

    if company_name is not None:
        fields.append("company_name = ?")
        params.append(company_name.strip() or None)
    if first_name is not None:
        fields.append("first_name = ?")
        params.append(first_name.strip() or None)
    if last_name is not None:
        fields.append("last_name = ?")
        params.append(last_name.strip() or None)
    if phone_cc is not None:
        fields.append("phone_cc = ?")
        params.append(phone_cc.strip() or None)
    if phone is not None:
        fields.append("phone = ?")
        params.append(phone.strip() or None)
    if email is not None:
        em = email.strip()
        if em and not EMAIL_RE.match(em):
            raise UserError(f"Email inválido: {em}")
        fields.append("email = ?")
        params.append(em or None)
    if telegram_chat_id is not None:
        tg = telegram_chat_id.strip()
        fields.append("telegram_chat_id = ?")
        params.append(tg or None)
    if telegram_off is not None:
        fields.append("telegram_off = ?")
        params.append(telegram_off.strip() or None)
    if telegram_bot_token is not None:
        fields.append("telegram_bot_token = ?")
        params.append(telegram_bot_token.strip() or None)
    if tenant_quota is not None:
        if tenant_quota < 0:
            raise UserError("Quota inválida (debe ser ≥ 0).")
        fields.append("tenant_quota = ?")
        params.append(tenant_quota)
    if role is not None:
        if role not in ROLES:
            raise UserError(f"Rol inválido. Usar uno de: {', '.join(ROLES)}")
        fields.append("role = ?")
        params.append(role)
    if new_password is not None and new_password != "":
        if enforce_complexity:
            validate_password_complexity(new_password)
        fields.append("password_hash = ?")
        params.append(hash_password(new_password))
    if clear_must_change:
        fields.append("must_change_password = 0")

    if not fields:
        return user

    params.append(user_id)
    with connect() as con:
        con.execute(f"UPDATE users SET {', '.join(fields)} WHERE id = ?", params)
    return get_user(user_id)


def delete_user(user_id: int) -> None:
    user = get_user(user_id)
    if not user:
        raise UserError("Usuario no encontrado.")
    if count_user_tenants(user_id) > 0:
        raise UserError("El usuario tiene tenants. Borralos antes o reasigná el dueño.")
    with connect() as con:
        # Bloquear borrado del último admin
        admins = con.execute("SELECT COUNT(*) AS c FROM users WHERE role = 'admin'").fetchone()["c"]
        if user["role"] == "admin" and admins <= 1:
            raise UserError("No se puede borrar el último admin.")
        con.execute("DELETE FROM users WHERE id = ?", (user_id,))


def seed_initial_admin(username: str, password_hash: str) -> Optional[dict]:
    """Si no hay usuarios en la DB, crea el admin inicial con el hash bcrypt del env.
    Marca must_change_password=1 para forzar cambio en el primer login.
    También adopta tenants huérfanos (sin owner_id) bajo este admin."""
    with connect() as con:
        count = con.execute("SELECT COUNT(*) AS c FROM users").fetchone()["c"]
    if count > 0:
        return None
    if not username or not password_hash:
        return None

    with connect() as con:
        cur = con.execute(
            """INSERT INTO users
               (username, password_hash, role, company_name, tenant_quota,
                must_change_password, created_at)
               VALUES (?, ?, 'admin', 'Administración', NULL, 1, ?)""",
            (username, password_hash, now_iso()),
        )
        admin_id = cur.lastrowid
        # Adoptar tenants huérfanos
        con.execute("UPDATE tenants SET owner_id = ? WHERE owner_id IS NULL", (admin_id,))
    return get_user(admin_id)
